/********************************************/
/*     Authors: Omar, Mariam & Anwar		*/
/********************************************/

#ifndef HLED_MATRIX_CONFIG_H_
#define HLED_MATRIX_CONFIG_H_

#define LED_MATRIX_ROWS_PORT    	GPIO_PORTB
#define LED_MATRIX_COL_PORT    		GPIO_PORTA

//#define LED_MATRIX_ROW0_PORT		GPIO_PORTA
//#define LED_MATRIX_ROW1_PORT		GPIO_PORTA
//#define LED_MATRIX_ROW2_PORT		GPIO_PORTA
//#define LED_MATRIX_ROW3_PORT		GPIO_PORTB
//#define LED_MATRIX_ROW4_PORT		GPIO_PORTB
//#define LED_MATRIX_ROW5_PORT		GPIO_PORTB
//#define LED_MATRIX_ROW6_PORT		GPIO_PORTB
//#define LED_MATRIX_ROW7_PORT		GPIO_PORTB
//
//#define LED_MATRIX_COL0_PORT		GPIO_PORTB
//#define LED_MATRIX_COL1_PORT		GPIO_PORTB
//#define LED_MATRIX_COL2_PORT		GPIO_PORTB
//#define LED_MATRIX_COL3_PORT		GPIO_PORTB
//#define LED_MATRIX_COL4_PORT		GPIO_PORTB
//#define LED_MATRIX_COL5_PORT		GPIO_PORTB
//#define LED_MATRIX_COL6_PORT		GPIO_PORTB
//#define LED_MATRIX_COL7_PORT		GPIO_PORTB


#define LED_MATRIX_ROW0_PIN			GPIO_PIN0
#define LED_MATRIX_ROW1_PIN			GPIO_PIN1
#define LED_MATRIX_ROW2_PIN			GPIO_PIN2
#define LED_MATRIX_ROW3_PIN			GPIO_PIN5
#define LED_MATRIX_ROW4_PIN			GPIO_PIN6
#define LED_MATRIX_ROW5_PIN			GPIO_PIN7
#define LED_MATRIX_ROW6_PIN			GPIO_PIN8
#define LED_MATRIX_ROW7_PIN			GPIO_PIN9

#define LED_MATRIX_COL0_PIN			GPIO_PIN3
#define LED_MATRIX_COL1_PIN			GPIO_PIN4
#define LED_MATRIX_COL2_PIN			GPIO_PIN5
#define LED_MATRIX_COL3_PIN			GPIO_PIN6
#define LED_MATRIX_COL4_PIN			GPIO_PIN7
#define LED_MATRIX_COL5_PIN			GPIO_PIN8
#define LED_MATRIX_COL6_PIN			GPIO_PIN11
#define LED_MATRIX_COL7_PIN			GPIO_PIN12


#endif /* HLED_MATRIX_CONFIG_H_ */
